version: "3.8"
# Local development compose (optional, not used on EC2 since user_data writes its own)
services:
  moodle:
    image: bitnami/moodle:latest
    ports: ["8080:8080"]
    environment:
      - MOODLE_DATABASE_HOST=127.0.0.1
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=ChangeMe123!
      - MOODLE_DATABASE_NAME=moodle
    volumes:
      - moodledata:/bitnami/moodle
      - moodledata:/bitnami/moodledata

  nginx:
    image: nginx:stable
    depends_on: ["moodle"]
    ports: ["80:80"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  moodledata:
